Display Languages feature
csys-fresher-batch-2021/musicapp-gokul pull request #1
Opened 2021-05-10 13:36 UTC by gogulram

2021-05-12 12:23 UTC, csys-fresher-batch-2021 commented on backup/NewUserRegistration.jsp
> +<html lang="en" >
Remove Registration page.

2021-05-12 12:23 UTC, csys-fresher-batch-2021 commented on src/main/java/in/gokul/services/LanguageServices.java
> +	private static final List <Languages> LanguageList= new ArrayList<>();
Follow naming convention

2021-05-12 12:23 UTC, csys-fresher-batch-2021 commented on src/main/java/in/gokul/services/LanguageServices.java
> +
Format the code.

2021-05-12 12:24 UTC, csys-fresher-batch-2021 commented on src/test/Login.jsp
> +<html lang="en" >
Delete Login page

2021-05-12 12:24 UTC, csys-fresher-batch-2021 requested changes
Remove unnecessary files like Register and Login

2021-05-12 12:58 UTC, gogulram commented on backup/NewUserRegistration.jsp
> +<html lang="en" >
removed

2021-05-12 12:58 UTC, gogulram commented on src/main/java/in/gokul/services/LanguageServices.java
> +	private static final List <Languages> LanguageList= new ArrayList<>();
Changed

2021-05-12 12:58 UTC, gogulram commented on src/main/java/in/gokul/services/LanguageServices.java
> +
formated the code

2021-05-12 12:58 UTC, gogulram commented on src/test/Login.jsp
> +<html lang="en" >
deleted

2021-05-13 08:48 UTC, csys-fresher-batch-2021 commented on src/main/java/in/gokul/model/Languages.java
> +public class Languages {
Rename to Language.

2021-05-13 08:49 UTC, csys-fresher-batch-2021 commented on src/main/java/in/gokul/services/LanguageServices.java
> +	public static boolean isLanguageAvailable(String language) {
This method is not related to Display language feature.

2021-05-13 08:50 UTC, csys-fresher-batch-2021 requested changes
Review comments added

2021-05-13 09:16 UTC, csys-fresher-batch-2021 commented on src/main/java/in/gokul/services/LanguageServices.java
> +	}
Format the code

2021-05-13 09:17 UTC, csys-fresher-batch-2021 commented on src/main/webapp/languages.jsp
> +		String loggedInUsername = (String)session.getAttribute("Logged_In_User");
Remove LoggedInUserDetails

2021-05-13 09:18 UTC, csys-fresher-batch-2021 commented on src/test/java/in/gokul/ServicesTest/LanguageTest.java
> +	public void TotalLanguagesCount() {
Follow naming convention

2021-05-13 09:18 UTC, csys-fresher-batch-2021 commented on src/main/java/in/gokul/validation/Validation.java
> +			if ((language == null) || (language.trim().equals(" ")) ) {
.equals("")

2021-05-13 09:19 UTC, csys-fresher-batch-2021 requested changes
Remove code which is not relevant to this feature.

2021-05-13 09:43 UTC, csys-fresher-batch-2021 commented on src/main/java/in/gokul/services/LanguageServices.java
> +
thank you.

2021-05-13 09:44 UTC, csys-fresher-batch-2021 approved these changes
LGTM

2021-05-13 09:44 UTC, merged